language: haskell
ghc: 7.8
before_install:
  - sudo apt-get install software-properties-common python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-lxc/stable
  - sudo apt-get update -qq
  - sudo apt-get install -y lxc-dev
install:
  - cabal install --force-reinstalls alex happy
  - git clone https://github.com/fizruk/trass-lxc.git && cd trass-lxc && cabal install && cd ..
  - cabal install --only-dependencies --enable-tests
